language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest --cov=pipedream_solver/
after_success:
  - coveralls
